FROM python:3-alpine AS builder

WORKDIR /app

COPY app/requirements.txt requirements.txt

RUN pip install --no-cache-dir --prefix=/install -r requirements.txt 

COPY . .

FROM gcr.io/distroless/python3

WORKDIR /app

COPY --from=builder /install /usr/local
COPY --from=builder /app /app

CMD ["python", "app/app.py"]
